name: cimawy
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: 6.1.0
  flutter_screenutil: ^5.9.0
  provider: ^6.1.2
  dio: ^5.4.2+1
  flutter_image_slideshow: ^0.1.6
  cached_network_image: ^3.3.1
  shared_preferences: ^2.2.3
  equatable: ^2.0.5
  dartz: ^0.10.1
  bloc: ^8.1.4
  flutter_bloc: ^8.1.5
  injectable: ^2.3.5
  get_it: ^7.6.7
  freezed: ^2.5.2
  flutter_native_splash: ^2.3.11
  flutter_launcher_icons: ^0.13.1
  youtube_player_flutter: ^8.1.2




flutter_launcher_icons:
  android: true
  ios: true
  adaptive_icon_foreground: "assets/images/ic_launcher.png"
  image_path: "assets/images/ic_launcher.png"
  adaptive_icon_background: "#000000"
  remove_alpha_ios: true



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.9
  injectable_generator: ^2.4.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/gens/
